### ISSUE TITLE
Duplicated submissions and edits

### ISSUE THREAD

**Issue by unode** [Research-Support-Network/research-support-network.github.io#16]
The current engine configuration treats every submission as unique as it includes a unique **id**entifier in the filename.

We could use a different field but we would still need to have enough information to not have identity clashes.
All combinations I can think of have some form of caveat.
For instance:
  * `Name-Affiliation` will likely not be unique enough.
  * `Email` may be sufficient but will need manual update if members relocate.
  * ...

We should also test if submitting different data (e.g. expertise) to an existing email record will be treated as an edit or something else will happen.

**Comment by WhoIsJack** [comment]
+1 for testing things!

I'm tempted to think that the unique identifier is actually a good solution. There may be the occasional duplicate, but so long as the entries do not interact, this shouldn't harm the list's functionality. There's also the possibility of occasionally running some simple code off-line to highlight possible duplicates, which can then be deleted manually.

In other words, I'd rather err on the side of having duplicates in the list than rejecting genuine entries because they look like duplicates to a simple algorithm.

Re edits: this could be difficult to provide as a functionality, as it would require authentication so people can't just submit different data for existing entries. That's another reason why I think IDed, non-interactive entries are best for now, to keep it simple.

Re existing email record: I would anyway opt to change the email field to just another text field in order to allow email obfuscation, in which case any new submission using the same email will just generate an independent duplicate, which we can handle by off-line monitoring as mentioned above.

Actually, this just gave me an idea, but I'm opening a new issue for that.

**Comment by WhoIsJack** [comment]
Unless dupes are involved in #13, I don't think they're a huge problem and as mentioned above we can always resolve them offline. Closing.
